model:
  name: "adaptive_frequency_ssm_base"
  d_model: 512
  n_layer: 12
  vocab_size: 50304
  d_state: 64
  d_conv: 4
  expand: 2
  compression_ratio: 0.5
  use_adaptive_mask: true
  use_spectral_norm: true
  use_multi_scale: true
  num_scales: 3
  dropout: 0.1
  max_seq_len: 2048

training:
  batch_size: 32
  max_steps: 100000
  max_epochs: 100
  learning_rate: 1e-4
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.95
  grad_clip_norm: 1.0
  warmup_steps: 1000
  lr_decay_steps: 80000
  min_lr_ratio: 0.1
  use_amp: true
  amp_dtype: "float16"
  label_smoothing: 0.0

data:
  dataset_name: "lra"
  task_name: "listops"
  data_dir: "./data"
  num_workers: 4
  pin_memory: true

logging:
  save_dir: "./checkpoints"
  log_interval: 100
  eval_interval: 1000
  save_interval: 5000
  wandb_project: "adaptive_frequency_ssm"
  wandb_name: null

system:
  device: "cuda"
  compile_model: true
  distributed: false